config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "ask", to: 'questions#ask'
  get "answer", to: "questions#answer"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def ask 
  end

  def answer
    if params[:question]
      @question = params[:question]
    end
    if @question == "I am going to work"
      @answer = "Great!"
    elsif @question[-1] == "?"
      @answer = "Silly question, get dressed and go to work!"
    else
      @answer = "I don't care, get dressed and go to work!"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsStupidCoaching</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <h1 class="center padding">Stupid Coaching</h1>
    <%= yield %>
  </body>
</html>

app/views/questions/answer.html.erb
<div class="center">
  <div class="left-border padding">
    <h2>You asked:</h2>
    <h3>- <em><%= @question %></em></h3>
  </div>
  <br>
  <div class="left-border padding" id="coach">
    <h2>Coach says:</h2>
    <h3>- <em><%= @answer %></em></h3>
  </div>
  <br>
  <%= link_to  "Ask another question", ask_path %>
</div>

app/views/questions/ask.html.erb
<div class="center">
  <h2>Ask your coach anything:</h2>
    <form action="/answer">
      <input class="search" type="text" name="question">
      <input class="submit-btn" type="submit" value="Ask!">
    </form>
</div>